# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinablue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeinfor',
            name='openid',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
