# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinablue', '0003_traineeinfor_wxinfor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinablueUserInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=60, null=True)),
                ('wxInfor', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
